name: GitHub Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Roda todo dia à meia-noite
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          base: header, repositories, metadata
          config_timezone: America/Sao_Paulo

          # --- Plugins visuais e avançados ---
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: percentage, bytes-size, lines
          plugin_languages_limit: 10

          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all

          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: B

          plugin_lines: yes
          plugin_followup: yes

          # Opcional: tempo real de dev (precisa integrar com Wakatime depois)
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, languages, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}

      - name: Commit metrics
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add github-metrics.svg
          git commit -m "chore: update metrics" || echo "No changes to commit"
          git push
