name: GitHub Metrics
on:
  schedule: [{cron: "0 * * * *"}] # Atualiza a cada 1 hora
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          # 🏆 Plugins ativos
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, languages, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}

          plugin_achievements: no   # desabilitado pq tá quebrando
