name: GitHub Metrics
on:
  schedule:
    - cron: "0 * * * *" # roda todo início de hora
  workflow_dispatch:      # permite rodar manualmente

permissions:
  contents: write         # 🔑 permite commitar no repositório

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          base: header, repositories, metadata
          config_timezone: America/Sao_Paulo

          # 📊 Plugins ativos
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: percentage, bytes-size, lines
          plugin_languages_limit: 8

          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all

          plugin_lines: yes
          plugin_followup: yes

          # ⏱️ Wakatime
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, languages, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}

      - name: Commit metrics
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add github-metrics.svg
          git commit -m "chore: update metrics [skip ci]" || echo "No changes"
          git push
