name: GitHub Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # roda todo dia à meia-noite
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          base: header, repositories, metadata
          config_timezone: America/Sao_Paulo

          # Plugins extras
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: percentage, bytes-size

          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          plugin_isocalendar: yes

          plugin_achievements: yes
          plugin_lines: yes

      - name: Commit metrics
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add github-metrics.svg
          git commit -m "chore: update metrics" || echo "No changes to commit"
          git push
