name: GitHub Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Roda 1x por dia à meia-noite
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories, metadata
          config_timezone: America/Sao_Paulo

          # Plugins extras
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: percentage, bytes-size

          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          plugin_isocalendar: yes

          plugin_achievements: yes
          plugin_lines: yes
